on:
  workflow_run:
    workflows:
      - "Test"
    tags:
      - release/*
    types:
      - completed

name: Release Packaging

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: sling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: echo "RELEASE=$(echo "${{ github.ref }}" | sed -i 's|release/||')" >>$GITHUB_ENV
      - run: echo "$RELEASE"
      - run: exit 1
      - run: test -e changelog/${{ github.ref }}.md
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: changelog/${{ github.ref }}.md
          draft: false
          prerelease: false
