on:
  push:
    tags:
      - release/*

name: Release

jobs:
  check:
    name: Check Release
    env:
      PROJECT_NAME_UNDERSCORE: sling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "RELEASE=$(basename "${{ github.ref }}")" >>$GITHUB_ENV
      - run: test -e changelog/${RELEASE}.md

  analyze:
    uses: ./.github/workflows/analyze.yml

  release:
    name: Release
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "RELEASE=$(basename "${{ github.ref }}")" >>$GITHUB_ENV
      - run: test -e changelog/${RELEASE}.md
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: changelog/${{ env.RELEASE }}.md
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE }}

  build:
    name: Build
    needs: release
    env:
      PROJECT_NAME_UNDERSCORE: sling
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            asset: sling-windows-amd64
            artifact: sling.exe
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            asset: sling-linux-amd64
            artifact: sling
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            asset: sling-macos-amd64
            artifact: sling
            target: x86_64-apple-darwin
          - os: macos-latest
            asset: sling-macos-aarch64
            artifact: sling
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: stable
          override: true
      - name: Install Dependencies (Linux)
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt-get install -y musl-tools
      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact }}
          asset_name: ${{ matrix.asset }}
          tag: ${{ github.ref }}
