on:
  push:
    tags:
      - release/*

name: Release

jobs:
  check:
    name: Check Release
    env:
      PROJECT_NAME_UNDERSCORE: sling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "RELEASE=$(basename "${{ github.ref }}")" >>$GITHUB_ENV
      - run: test -e changelog/${RELEASE}.md
  release-draft:
    name: Draft Release
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "RELEASE=$(basename "${{ github.ref }}")" >>$GITHUB_ENV
      - run: test -e changelog/${RELEASE}.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE }}
          body_path: changelog/${{ env.RELEASE }}.md
          draft: false
          prerelease: false
