on:
  push:
    tags:
      - release/*

name: Release

jobs:
  check:
    name: Check Release
    env:
      PROJECT_NAME_UNDERSCORE: sling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: echo "RELEASE=$(basename "${{ github.ref }}")" >>$GITHUB_ENV
      - run: test -e changelog/${RELEASE}.md
  release-draft:
    name: Draft Release
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: echo "RELEASE=$(basename "${{ github.ref }}")" >>$GITHUB_ENV
      - run: test -e changelog/${RELEASE}.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE }}
          body_path: changelog/${{ env.RELEASE }}.md
          draft: false
          prerelease: false
  build:
    name: Build
    needs: release-draft
    env:
      PROJECT_NAME_UNDERSCORE: sling
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          RUSTTARGET: ${{ matrix.target }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}