on:
  pull_request:
  push:
    branches:
      - main

name: Analyze

jobs:
  analyze:
    uses: ./.github/workflows/analyze.yml
    with:
      cache_key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
