on:
  release:
    types:
      - published

name: Release

jobs:
  build:
    name: Build
    env:
      PROJECT_NAME_UNDERSCORE: sling
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - asset: sling-windows-amd64
            target: x86_64-pc-windows-gnu
          - asset: sling-linux-amd64
            target: x86_64-unknown-linux-musl
          - asset: sling-macos-amd64
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          RUSTTARGET: ${{ matrix.target }}
